global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "node exporter"
    static_configs:
      - targets:
          - "192.168.2.126:9100"

  - job_name: "cAdvisor"
    static_configs:
      - targets:
          - "192.168.2.126:8080"

  - job_name: "eBPF exporter"
    static_configs:
      - targets:
          - "192.168.2.126:9435"

  - job_name: "cgroups exporter"
    static_configs:
      - targets:
          - "192.168.2.126:9753" 
 
  - job_name: "slurm-job exporter"
    static_configs:
      - targets:
          - "192.168.2.126:9101"

  - job_name: 'process exporter'
    static_configs:
      - targets: 
         - "192.168.2.126:9256"

         
  - job_name: 'scaphandre'
    static_configs:
      - targets: 
         - "192.168.2.126:8081"
